/*
 * Liste des entrées, plats et desserts de « On mange quoi ce soir ? »
 * --------------------------------------------------------------------
 * Une ligne par idée : { emoji, nom, type, tags }
 *
 * type :  'entree', 'plat' ou 'dessert'  (sans type, c'est un plat)
 *
 * Tags disponibles (ce sont les filtres de l'écran d'accueil) :
 *   rapide    → prêt en 30 minutes environ
 *   vege      → sans viande ni poisson
 *   leger     → plutôt léger
 *   reconfort → plat réconfortant
 *   commande  → se commande facilement en livraison
 *   france    → cuisine française
 *   monde     → cuisine du monde
 *
 * Pour ajouter une idée, copie une ligne, change-la, et n'oublie pas la virgule à la fin.
 */
window.PLATS = [
  // ======================================================================
  // PLATS  (type absent = plat)
  // ======================================================================

  // ---------- Cuisine française ----------
  { emoji: '🍲', nom: 'Pot-au-feu',                    tags: ['reconfort', 'france'] },
  { emoji: '🍷', nom: 'Bœuf bourguignon',              tags: ['reconfort', 'france'] },
  { emoji: '🍲', nom: 'Blanquette de veau',            tags: ['reconfort', 'france'] },
  { emoji: '🐓', nom: 'Coq au vin',                    tags: ['reconfort', 'france'] },
  { emoji: '🫘', nom: 'Cassoulet',                     tags: ['reconfort', 'france'] },
  { emoji: '🥬', nom: 'Choucroute garnie',             tags: ['reconfort', 'france'] },
  { emoji: '🥔', nom: 'Tartiflette',                   tags: ['reconfort', 'france'] },
  { emoji: '🧀', nom: 'Raclette',                      tags: ['reconfort', 'france'] },
  { emoji: '🫕', nom: 'Fondue savoyarde',              tags: ['vege', 'reconfort', 'france'] },
  { emoji: '🥘', nom: 'Aligot saucisse',               tags: ['reconfort', 'france'] },
  { emoji: '🍲', nom: 'Potée auvergnate',              tags: ['reconfort', 'france'] },
  { emoji: '🐖', nom: 'Petit salé aux lentilles',      tags: ['reconfort', 'france'] },
  { emoji: '🥔', nom: 'Hachis parmentier',             tags: ['reconfort', 'france'] },
  { emoji: '🥔', nom: 'Gratin dauphinois',             tags: ['vege', 'reconfort', 'france'] },
  { emoji: '🥓', nom: 'Endives au jambon',             tags: ['reconfort', 'france'] },
  { emoji: '🍅', nom: 'Tomates farcies',               tags: ['reconfort', 'france'] },
  { emoji: '🥧', nom: 'Quiche lorraine',               tags: ['reconfort', 'france'] },
  { emoji: '🥧', nom: 'Tarte tomate-moutarde',         tags: ['vege', 'france'] },
  { emoji: '🥓', nom: 'Tarte flambée',                 tags: ['reconfort', 'france'] },
  { emoji: '🥧', nom: 'Bouchées à la reine',           tags: ['reconfort', 'france'] },
  { emoji: '🧅', nom: "Soupe à l'oignon gratinée",     tags: ['vege', 'reconfort', 'france'] },
  { emoji: '🥣', nom: 'Soupe de légumes',              tags: ['vege', 'leger', 'france'] },
  { emoji: '🍆', nom: 'Ratatouille',                   tags: ['vege', 'leger', 'france'] },
  { emoji: '🥪', nom: 'Croque-monsieur',               tags: ['rapide', 'reconfort', 'france'] },
  { emoji: '🍳', nom: 'Croque-madame',                 tags: ['rapide', 'reconfort', 'france'] },
  { emoji: '🧀', nom: 'Tartines gratinées',            tags: ['rapide', 'reconfort', 'france'] },
  { emoji: '🍺', nom: 'Welsh',                         tags: ['reconfort', 'france'] },
  { emoji: '🍗', nom: 'Poulet rôti & frites',          tags: ['reconfort', 'france'] },
  { emoji: '🥩', nom: 'Steak frites',                  tags: ['rapide', 'reconfort', 'france'] },
  { emoji: '🍖', nom: 'Rôti de porc & haricots verts', tags: ['reconfort', 'france'] },
  { emoji: '🦆', nom: 'Magret de canard',              tags: ['france'] },
  { emoji: '🌭', nom: 'Saucisse-purée',                tags: ['rapide', 'reconfort', 'france'] },
  { emoji: '🍝', nom: 'Coquillettes jambon-fromage',   tags: ['rapide', 'reconfort', 'france'] },
  { emoji: '🦪', nom: 'Moules-frites',                 tags: ['reconfort', 'france'] },
  { emoji: '🐟', nom: 'Bouillabaisse',                 tags: ['reconfort', 'france'] },
  { emoji: '🐟', nom: 'Brandade de morue',             tags: ['reconfort', 'france'] },
  { emoji: '🐚', nom: 'Coquilles Saint-Jacques',       tags: ['leger', 'france'] },
  { emoji: '🐟', nom: 'Poisson en papillote',          tags: ['rapide', 'leger', 'france'] },
  { emoji: '🥗', nom: 'Salade niçoise',                tags: ['rapide', 'leger', 'france'] },
  { emoji: '🐐', nom: 'Salade de chèvre chaud',        tags: ['rapide', 'vege', 'france'] },
  { emoji: '🥚', nom: 'Œufs mayo & crudités',          tags: ['rapide', 'vege', 'leger', 'france'] },
  { emoji: '🍄', nom: 'Omelette aux champignons',      tags: ['rapide', 'vege', 'leger', 'france'] },
  { emoji: '🥞', nom: 'Galettes complètes',            tags: ['rapide', 'france'] },
  { emoji: '🥞', nom: 'Soirée crêpes',                 tags: ['rapide', 'vege', 'reconfort', 'france'] },
  { emoji: '🧀', nom: 'Plateau apéro dînatoire',       tags: ['rapide', 'france'] },

  // ---------- Italie ----------
  { emoji: '🥓', nom: 'Pâtes carbonara',               tags: ['rapide', 'reconfort', 'monde'] },
  { emoji: '🍅', nom: 'Pâtes bolognaise',              tags: ['rapide', 'reconfort', 'monde'] },
  { emoji: '🌿', nom: 'Pâtes au pesto',                tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🧀', nom: 'Pâtes cacio e pepe',            tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🦐', nom: 'Pâtes aux fruits de mer',       tags: ['monde'] },
  { emoji: '🍝', nom: 'Lasagnes',                      tags: ['reconfort', 'monde'] },
  { emoji: '🍝', nom: 'Cannellonis ricotta-épinards',  tags: ['vege', 'reconfort', 'monde'] },
  { emoji: '🥔', nom: 'Gnocchis sauce tomate',         tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🍄', nom: 'Risotto aux champignons',       tags: ['vege', 'reconfort', 'monde'] },
  { emoji: '🍕', nom: 'Pizza',                         tags: ['reconfort', 'commande', 'monde'] },
  { emoji: '🍕', nom: 'Pizza maison',                  tags: ['reconfort', 'monde'] },
  { emoji: '🍆', nom: 'Aubergines à la parmesane',     tags: ['vege', 'reconfort', 'monde'] },
  { emoji: '🥩', nom: 'Osso buco',                     tags: ['reconfort', 'monde'] },
  { emoji: '🥣', nom: 'Minestrone',                    tags: ['vege', 'leger', 'monde'] },
  { emoji: '🥖', nom: 'Bruschettas',                   tags: ['rapide', 'vege', 'leger', 'monde'] },
  { emoji: '🫓', nom: 'Piadinas',                      tags: ['rapide', 'monde'] },

  // ---------- Espagne & Portugal ----------
  { emoji: '🥘', nom: 'Paella',                        tags: ['reconfort', 'monde'] },
  { emoji: '🥔', nom: 'Tortilla espagnole',            tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🍢', nom: 'Soirée tapas',                  tags: ['monde'] },
  { emoji: '🍅', nom: 'Gaspacho',                      tags: ['rapide', 'vege', 'leger', 'monde'] },
  { emoji: '🦐', nom: "Crevettes à l'ail",             tags: ['rapide', 'leger', 'monde'] },
  { emoji: '🐟', nom: 'Bacalhau à brás',               tags: ['monde'] },

  // ---------- Grèce, Moyen-Orient & Maghreb ----------
  { emoji: '🍆', nom: 'Moussaka',                      tags: ['reconfort', 'monde'] },
  { emoji: '🥗', nom: 'Salade grecque',                tags: ['rapide', 'vege', 'leger', 'monde'] },
  { emoji: '🥙', nom: 'Pitas gyros',                   tags: ['rapide', 'commande', 'monde'] },
  { emoji: '🥙', nom: 'Kebab',                         tags: ['commande', 'monde'] },
  { emoji: '🧆', nom: 'Falafels & houmous',            tags: ['vege', 'leger', 'monde'] },
  { emoji: '🥒', nom: 'Taboulé libanais',              tags: ['rapide', 'vege', 'leger', 'monde'] },
  { emoji: '🍢', nom: 'Brochettes grillées',           tags: ['monde'] },
  { emoji: '🥘', nom: 'Couscous',                      tags: ['reconfort', 'monde'] },
  { emoji: '🫔', nom: 'Tajine',                        tags: ['reconfort', 'monde'] },
  { emoji: '🍳', nom: 'Chakchouka',                    tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🥟', nom: 'Bricks au thon',                tags: ['rapide', 'monde'] },
  { emoji: '🥣', nom: 'Soupe de lentilles corail',     tags: ['vege', 'leger', 'monde'] },

  // ---------- Afrique & Antilles ----------
  { emoji: '🥜', nom: 'Mafé',                          tags: ['reconfort', 'monde'] },
  { emoji: '🍋', nom: 'Poulet yassa',                  tags: ['reconfort', 'monde'] },
  { emoji: '🍌', nom: 'Alloco & poisson braisé',       tags: ['monde'] },
  { emoji: '🍛', nom: 'Colombo de poulet',             tags: ['reconfort', 'monde'] },
  { emoji: '🐟', nom: 'Accras de morue',               tags: ['monde'] },

  // ---------- Japon & Corée ----------
  { emoji: '🍣', nom: 'Sushis',                        tags: ['leger', 'commande', 'monde'] },
  { emoji: '🍜', nom: 'Ramen',                         tags: ['reconfort', 'commande', 'monde'] },
  { emoji: '🍛', nom: 'Curry japonais',                tags: ['reconfort', 'monde'] },
  { emoji: '🍱', nom: 'Bento japonais',                tags: ['leger', 'commande', 'monde'] },
  { emoji: '🥟', nom: 'Gyozas',                        tags: ['commande', 'monde'] },
  { emoji: '🍚', nom: 'Donburi au poulet',             tags: ['rapide', 'monde'] },
  { emoji: '🍤', nom: 'Tempuras',                      tags: ['monde'] },
  { emoji: '🍢', nom: 'Yakitoris',                     tags: ['monde'] },
  { emoji: '🥘', nom: 'Bibimbap',                      tags: ['leger', 'monde'] },
  { emoji: '🍗', nom: 'Poulet frit coréen',            tags: ['reconfort', 'commande', 'monde'] },
  { emoji: '🍲', nom: 'Kimchi jjigae',                 tags: ['reconfort', 'monde'] },

  // ---------- Chine & Asie du Sud-Est ----------
  { emoji: '🍚', nom: 'Riz cantonais',                 tags: ['rapide', 'monde'] },
  { emoji: '🥟', nom: 'Raviolis chinois vapeur',       tags: ['commande', 'monde'] },
  { emoji: '🦆', nom: 'Canard laqué',                  tags: ['commande', 'monde'] },
  { emoji: '🥢', nom: 'Nouilles sautées au bœuf',      tags: ['rapide', 'monde'] },
  { emoji: '🍗', nom: 'Poulet général Tao',            tags: ['commande', 'monde'] },
  { emoji: '🥢', nom: 'Tofu sauté au sésame',          tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🥢', nom: 'Wok de légumes & nouilles',     tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🥜', nom: 'Pad thaï',                      tags: ['rapide', 'commande', 'monde'] },
  { emoji: '🍛', nom: 'Curry vert thaï',               tags: ['reconfort', 'commande', 'monde'] },
  { emoji: '🍜', nom: 'Phở',                           tags: ['leger', 'reconfort', 'commande', 'monde'] },
  { emoji: '🥢', nom: 'Bò bún',                        tags: ['leger', 'commande', 'monde'] },
  { emoji: '🥖', nom: 'Bánh mì',                       tags: ['rapide', 'commande', 'monde'] },
  { emoji: '🥬', nom: 'Rouleaux de printemps',         tags: ['leger', 'monde'] },
  { emoji: '🍜', nom: 'Laksa',                         tags: ['reconfort', 'monde'] },

  // ---------- Inde ----------
  { emoji: '🍛', nom: 'Butter chicken',                tags: ['reconfort', 'commande', 'monde'] },
  { emoji: '🍛', nom: 'Poulet tikka masala',           tags: ['reconfort', 'commande', 'monde'] },
  { emoji: '🍛', nom: 'Curry de pois chiches',         tags: ['vege', 'reconfort', 'monde'] },
  { emoji: '🫘', nom: 'Dal de lentilles',              tags: ['vege', 'reconfort', 'monde'] },
  { emoji: '🥬', nom: 'Palak paneer',                  tags: ['vege', 'monde'] },
  { emoji: '🍚', nom: 'Biryani',                       tags: ['reconfort', 'commande', 'monde'] },
  { emoji: '🥟', nom: 'Samoussas',                     tags: ['commande', 'monde'] },

  // ---------- Amériques ----------
  { emoji: '🌮', nom: 'Tacos mexicains',               tags: ['rapide', 'monde'] },
  { emoji: '🌯', nom: 'Burritos',                      tags: ['reconfort', 'commande', 'monde'] },
  { emoji: '🫔', nom: 'Enchiladas',                    tags: ['reconfort', 'monde'] },
  { emoji: '🧀', nom: 'Quesadillas',                   tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🥑', nom: 'Nachos & guacamole',            tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🌶️', nom: 'Chili con carne',               tags: ['reconfort', 'monde'] },
  { emoji: '🫘', nom: 'Chili sin carne',               tags: ['vege', 'reconfort', 'monde'] },
  { emoji: '🍔', nom: 'Burgers maison',                tags: ['reconfort', 'monde'] },
  { emoji: '🍔', nom: 'Burger végé',                   tags: ['vege', 'reconfort', 'monde'] },
  { emoji: '🌭', nom: 'Hot-dogs',                      tags: ['rapide', 'reconfort', 'monde'] },
  { emoji: '🍖', nom: 'Ribs sauce barbecue',           tags: ['reconfort', 'monde'] },
  { emoji: '🥪', nom: 'Club sandwich',                 tags: ['rapide', 'monde'] },
  { emoji: '🧀', nom: 'Mac & cheese',                  tags: ['vege', 'reconfort', 'monde'] },
  { emoji: '🥯', nom: 'Bagels saumon-fromage frais',   tags: ['rapide', 'leger', 'monde'] },
  { emoji: '🐟', nom: 'Ceviche',                       tags: ['leger', 'monde'] },
  { emoji: '🥟', nom: 'Empanadas',                     tags: ['monde'] },
  { emoji: '🫘', nom: 'Feijoada',                      tags: ['reconfort', 'monde'] },

  // ---------- Europe du Nord & de l'Est ----------
  { emoji: '🍟', nom: 'Fish & chips',                  tags: ['reconfort', 'monde'] },
  { emoji: '🥧', nom: "Shepherd's pie",                tags: ['reconfort', 'monde'] },
  { emoji: '🍲', nom: 'Goulash',                       tags: ['reconfort', 'monde'] },
  { emoji: '🥟', nom: 'Pierogis',                      tags: ['vege', 'reconfort', 'monde'] },
  { emoji: '🍖', nom: 'Boulettes suédoises',           tags: ['reconfort', 'monde'] },
  { emoji: '🌭', nom: 'Currywurst',                    tags: ['rapide', 'monde'] },
  { emoji: '🍳', nom: 'Rösti & œuf au plat',           tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🧀', nom: 'Spätzle au fromage',            tags: ['vege', 'reconfort', 'monde'] },
  { emoji: '🥣', nom: 'Bortsch',                       tags: ['vege', 'monde'] },
  { emoji: '🐟', nom: 'Saumon gravlax',                tags: ['leger', 'monde'] },

  // ---------- Simple, sain ou improvisé ----------
  { emoji: '🥗', nom: 'Salade César',                  tags: ['rapide', 'leger'] },
  { emoji: '🥬', nom: 'Buddha bowl',                   tags: ['vege', 'leger'] },
  { emoji: '🥑', nom: 'Poke bowl',                     tags: ['leger', 'commande'] },
  { emoji: '🌾', nom: 'Salade de quinoa',              tags: ['rapide', 'vege', 'leger'] },
  { emoji: '🍠', nom: 'Patates douces rôties & feta',  tags: ['vege', 'leger'] },
  { emoji: '🐟', nom: 'Saumon & riz',                  tags: ['rapide', 'leger'] },
  { emoji: '🍳', nom: 'Omelette & salade',             tags: ['rapide', 'vege', 'leger'] },
  { emoji: '🥘', nom: 'Poêlée de légumes & œuf',       tags: ['rapide', 'vege', 'leger'] },
  { emoji: '🥦', nom: 'Gratin de légumes',             tags: ['vege', 'reconfort'] },
  { emoji: '🍅', nom: 'Soupe tomate & grilled cheese', tags: ['rapide', 'vege', 'reconfort'] },
  { emoji: '🍝', nom: 'One-pot pasta',                 tags: ['rapide', 'vege', 'reconfort'] },
  { emoji: '🥥', nom: 'Poulet curry-coco',             tags: ['rapide', 'reconfort'] },
  { emoji: '🌯', nom: 'Wraps',                         tags: ['rapide'] },
  { emoji: '🔥', nom: 'Barbecue',                      tags: ['reconfort'] },
  { emoji: '🧇', nom: 'Brunch du soir',                tags: ['vege', 'reconfort'] },
  { emoji: '🧊', nom: 'Les restes du frigo',           tags: ['rapide', 'leger'] },

  // ======================================================================
  // ENTRÉES  (type: 'entree')
  // ======================================================================

  // ---------- Entrées françaises ----------
  { emoji: '🥚', nom: 'Œufs mimosa', type: 'entree', tags: ['rapide', 'vege', 'france'] },
  { emoji: '🥬', nom: 'Poireaux vinaigrette', type: 'entree', tags: ['vege', 'leger', 'france'] },
  { emoji: '🥕', nom: 'Carottes râpées au citron', type: 'entree', tags: ['rapide', 'vege', 'leger', 'france'] },
  { emoji: '🥗', nom: 'Céleri rémoulade', type: 'entree', tags: ['rapide', 'vege', 'leger', 'france'] },
  { emoji: '🫘', nom: 'Salade de lentilles vinaigrette', type: 'entree', tags: ['vege', 'leger', 'france'] },
  { emoji: '🥗', nom: 'Salade de betteraves & noix', type: 'entree', tags: ['rapide', 'vege', 'leger', 'france'] },
  { emoji: '🥔', nom: 'Salade piémontaise', type: 'entree', tags: ['reconfort', 'france'] },
  { emoji: '🥓', nom: 'Salade lyonnaise', type: 'entree', tags: ['france'] },
  { emoji: '🌸', nom: 'Radis beurre & fleur de sel', type: 'entree', tags: ['rapide', 'vege', 'leger', 'france'] },
  { emoji: '🌿', nom: 'Artichaut vinaigrette', type: 'entree', tags: ['vege', 'leger', 'france'] },
  { emoji: '🌱', nom: 'Asperges sauce mousseline', type: 'entree', tags: ['vege', 'leger', 'france'] },
  { emoji: '🍈', nom: 'Melon & jambon cru', type: 'entree', tags: ['rapide', 'leger', 'france'] },
  { emoji: '🐖', nom: 'Terrine de campagne & cornichons', type: 'entree', tags: ['rapide', 'france'] },
  { emoji: '🍞', nom: 'Rillettes sur pain grillé', type: 'entree', tags: ['rapide', 'france'] },
  { emoji: '🥧', nom: 'Pâté en croûte', type: 'entree', tags: ['france'] },
  { emoji: '🦆', nom: 'Foie gras & pain d\'épices', type: 'entree', tags: ['france'] },
  { emoji: '🐌', nom: 'Escargots au beurre persillé', type: 'entree', tags: ['france'] },
  { emoji: '🦪', nom: 'Plateau d\'huîtres', type: 'entree', tags: ['rapide', 'leger', 'france'] },
  { emoji: '🦐', nom: 'Avocat-crevettes', type: 'entree', tags: ['rapide', 'leger', 'france'] },
  { emoji: '🐟', nom: 'Saumon fumé & blinis', type: 'entree', tags: ['rapide', 'leger', 'france'] },
  { emoji: '🍣', nom: 'Tartare de saumon', type: 'entree', tags: ['rapide', 'leger', 'france'] },
  { emoji: '🐟', nom: 'Rillettes de thon', type: 'entree', tags: ['rapide', 'leger', 'france'] },
  { emoji: '🥚', nom: 'Œuf cocotte à la crème', type: 'entree', tags: ['rapide', 'vege', 'france'] },
  { emoji: '🍷', nom: 'Œufs en meurette', type: 'entree', tags: ['reconfort', 'france'] },
  { emoji: '🥚', nom: 'Œufs à la coque & mouillettes', type: 'entree', tags: ['rapide', 'vege', 'reconfort', 'france'] },
  { emoji: '🧀', nom: 'Gougères au comté', type: 'entree', tags: ['vege', 'france'] },
  { emoji: '🐐', nom: 'Toasts de chèvre au miel', type: 'entree', tags: ['rapide', 'vege', 'france'] },
  { emoji: '🍅', nom: 'Tartelettes tomate-chèvre', type: 'entree', tags: ['vege', 'france'] },
  { emoji: '🫒', nom: 'Cake salé olives-jambon', type: 'entree', tags: ['france'] },
  { emoji: '🥐', nom: 'Feuilletés à la saucisse', type: 'entree', tags: ['france'] },
  { emoji: '🧅', nom: 'Pissaladière', type: 'entree', tags: ['france'] },
  { emoji: '🫓', nom: 'Socca niçoise', type: 'entree', tags: ['rapide', 'vege', 'france'] },
  { emoji: '🍟', nom: 'Panisses', type: 'entree', tags: ['vege', 'france'] },
  { emoji: '🫒', nom: 'Tapenade & gressins', type: 'entree', tags: ['rapide', 'vege', 'france'] },
  { emoji: '🎃', nom: 'Velouté de potimarron', type: 'entree', tags: ['vege', 'leger', 'reconfort', 'france'] },
  { emoji: '🍄', nom: 'Velouté de champignons', type: 'entree', tags: ['vege', 'reconfort', 'france'] },
  { emoji: '🥦', nom: 'Crème Du Barry (chou-fleur)', type: 'entree', tags: ['vege', 'reconfort', 'france'] },
  { emoji: '🥔', nom: 'Soupe poireaux-pommes de terre', type: 'entree', tags: ['vege', 'reconfort', 'france'] },
  { emoji: '🫛', nom: 'Velouté petits pois-menthe', type: 'entree', tags: ['rapide', 'vege', 'leger', 'france'] },
  { emoji: '🐟', nom: 'Soupe de poissons & rouille', type: 'entree', tags: ['reconfort', 'france'] },
  { emoji: '🥬', nom: 'Terrine de légumes', type: 'entree', tags: ['vege', 'leger', 'france'] },
  { emoji: '🍄', nom: 'Champignons farcis', type: 'entree', tags: ['vege', 'france'] },

  // ---------- Entrées du monde ----------
  { emoji: '🧆', nom: 'Houmous & crudités', type: 'entree', tags: ['rapide', 'vege', 'leger', 'monde'] },
  { emoji: '🍆', nom: 'Caviar d\'aubergine', type: 'entree', tags: ['vege', 'leger', 'monde'] },
  { emoji: '🥒', nom: 'Tzatziki & pain pita', type: 'entree', tags: ['rapide', 'vege', 'leger', 'monde'] },
  { emoji: '🍇', nom: 'Feuilles de vigne farcies', type: 'entree', tags: ['vege', 'monde'] },
  { emoji: '🥗', nom: 'Fattouche', type: 'entree', tags: ['rapide', 'vege', 'leger', 'monde'] },
  { emoji: '🥕', nom: 'Salade de carottes au cumin', type: 'entree', tags: ['rapide', 'vege', 'leger', 'monde'] },
  { emoji: '🍅', nom: 'Zaalouk', type: 'entree', tags: ['vege', 'leger', 'monde'] },
  { emoji: '🍲', nom: 'Harira', type: 'entree', tags: ['reconfort', 'monde'] },
  { emoji: '🥙', nom: 'Assiette de mezzés', type: 'entree', tags: ['commande', 'monde'] },
  { emoji: '🧀', nom: 'Saganaki (fromage grillé)', type: 'entree', tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🧀', nom: 'Burrata & tomates cerises', type: 'entree', tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🍅', nom: 'Salade caprese', type: 'entree', tags: ['rapide', 'vege', 'leger', 'monde'] },
  { emoji: '🍖', nom: 'Vitello tonnato', type: 'entree', tags: ['monde'] },
  { emoji: '🫒', nom: 'Assiette d\'antipasti', type: 'entree', tags: ['rapide', 'monde'] },
  { emoji: '🍙', nom: 'Arancini', type: 'entree', tags: ['vege', 'monde'] },
  { emoji: '🥩', nom: 'Carpaccio de bœuf', type: 'entree', tags: ['rapide', 'leger', 'monde'] },
  { emoji: '🍉', nom: 'Salade pastèque-feta-menthe', type: 'entree', tags: ['rapide', 'vege', 'leger', 'monde'] },
  { emoji: '🍅', nom: 'Pan con tomate', type: 'entree', tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🥔', nom: 'Patatas bravas', type: 'entree', tags: ['vege', 'monde'] },
  { emoji: '🫑', nom: 'Pimientos de Padrón', type: 'entree', tags: ['rapide', 'vege', 'leger', 'monde'] },
  { emoji: '🥘', nom: 'Croquetas au jambon', type: 'entree', tags: ['monde'] },
  { emoji: '🍅', nom: 'Salmorejo', type: 'entree', tags: ['vege', 'leger', 'monde'] },
  { emoji: '🫑', nom: 'Poivrons marinés à l\'huile d\'olive', type: 'entree', tags: ['vege', 'leger', 'monde'] },
  { emoji: '🍤', nom: 'Tempura de légumes', type: 'entree', tags: ['vege', 'monde'] },
  { emoji: '🍤', nom: 'Crevettes tempura', type: 'entree', tags: ['commande', 'monde'] },
  { emoji: '🍜', nom: 'Soupe miso', type: 'entree', tags: ['rapide', 'leger', 'monde'] },
  { emoji: '🫛', nom: 'Edamame au sel', type: 'entree', tags: ['rapide', 'vege', 'leger', 'commande', 'monde'] },
  { emoji: '🥒', nom: 'Salade de concombre au sésame', type: 'entree', tags: ['rapide', 'vege', 'leger', 'monde'] },
  { emoji: '🐟', nom: 'Tataki de thon', type: 'entree', tags: ['rapide', 'leger', 'monde'] },
  { emoji: '🥢', nom: 'Nems', type: 'entree', tags: ['commande', 'monde'] },
  { emoji: '🧅', nom: 'Onion bhajis', type: 'entree', tags: ['vege', 'commande', 'monde'] },
  { emoji: '🍲', nom: 'Soupe tom kha kaï', type: 'entree', tags: ['leger', 'commande', 'monde'] },
  { emoji: '🥭', nom: 'Salade de papaye verte', type: 'entree', tags: ['leger', 'monde'] },
  { emoji: '🌽', nom: 'Elote (maïs grillé à la mexicaine)', type: 'entree', tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🥯', nom: 'Blinis & tarama', type: 'entree', tags: ['rapide', 'monde'] },
  { emoji: '🥑', nom: 'Toast avocat & œuf poché', type: 'entree', tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🍏', nom: 'Salade Waldorf', type: 'entree', tags: ['rapide', 'vege', 'leger', 'monde'] },
  { emoji: '🥥', nom: 'Velouté butternut coco-curry', type: 'entree', tags: ['vege', 'leger', 'reconfort', 'monde'] },

  // ======================================================================
  // DESSERTS  (type: 'dessert')
  // ======================================================================

  // ---------- Desserts français ----------
  { emoji: '🍫', nom: 'Mousse au chocolat', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🍮', nom: 'Crème brûlée', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '☁️', nom: 'Île flottante', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🍎', nom: 'Tarte Tatin', type: 'dessert', tags: ['vege', 'reconfort', 'france'] },
  { emoji: '🥧', nom: 'Tarte aux pommes', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🍋', nom: 'Tarte au citron meringuée', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🍓', nom: 'Tarte aux fraises', type: 'dessert', tags: ['vege', 'leger', 'france'] },
  { emoji: '🍐', nom: 'Tarte Bourdaloue (poires-amandes)', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🍫', nom: 'Tarte au chocolat', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🍑', nom: 'Tarte aux abricots', type: 'dessert', tags: ['vege', 'leger', 'france'] },
  { emoji: '🍬', nom: 'Tarte au sucre', type: 'dessert', tags: ['vege', 'reconfort', 'france'] },
  { emoji: '🍒', nom: 'Clafoutis aux cerises', type: 'dessert', tags: ['vege', 'reconfort', 'france'] },
  { emoji: '🥮', nom: 'Far breton', type: 'dessert', tags: ['vege', 'reconfort', 'france'] },
  { emoji: '🍫', nom: 'Fondant au chocolat', type: 'dessert', tags: ['rapide', 'vege', 'reconfort', 'france'] },
  { emoji: '🌋', nom: 'Moelleux au cœur coulant', type: 'dessert', tags: ['rapide', 'vege', 'reconfort', 'france'] },
  { emoji: '🍨', nom: 'Profiteroles', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '⚡', nom: 'Éclairs au chocolat', type: 'dessert', tags: ['vege', 'commande', 'france'] },
  { emoji: '🌰', nom: 'Paris-Brest', type: 'dessert', tags: ['vege', 'commande', 'france'] },
  { emoji: '🍰', nom: 'Mille-feuille', type: 'dessert', tags: ['vege', 'commande', 'france'] },
  { emoji: '🌈', nom: 'Macarons', type: 'dessert', tags: ['vege', 'commande', 'france'] },
  { emoji: '🍚', nom: 'Riz au lait', type: 'dessert', tags: ['vege', 'reconfort', 'france'] },
  { emoji: '🍮', nom: 'Crème caramel', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🥧', nom: 'Flan pâtissier', type: 'dessert', tags: ['vege', 'reconfort', 'france'] },
  { emoji: '🥛', nom: 'Œufs au lait', type: 'dessert', tags: ['rapide', 'vege', 'reconfort', 'france'] },
  { emoji: '🍫', nom: 'Crème au chocolat maison', type: 'dessert', tags: ['vege', 'reconfort', 'france'] },
  { emoji: '🍐', nom: 'Poire Belle-Hélène', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🍞', nom: 'Pain perdu', type: 'dessert', tags: ['rapide', 'vege', 'reconfort', 'france'] },
  { emoji: '🍊', nom: 'Crêpes Suzette', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🧇', nom: 'Gaufres & chantilly', type: 'dessert', tags: ['vege', 'reconfort', 'france'] },
  { emoji: '🍓', nom: 'Charlotte aux fraises', type: 'dessert', tags: ['france'] },
  { emoji: '🍓', nom: 'Fraisier', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🏔️', nom: 'Mont-Blanc aux marrons', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🍪', nom: 'Madeleines tièdes', type: 'dessert', tags: ['rapide', 'vege', 'france'] },
  { emoji: '🥮', nom: 'Financiers', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🍮', nom: 'Cannelés', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🧈', nom: 'Kouign-amann', type: 'dessert', tags: ['vege', 'reconfort', 'france'] },
  { emoji: '🍾', nom: 'Baba au rhum', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🍒', nom: 'Gâteau basque', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🧁', nom: 'Quatre-quarts', type: 'dessert', tags: ['vege', 'reconfort', 'france'] },
  { emoji: '🥛', nom: 'Gâteau au yaourt', type: 'dessert', tags: ['rapide', 'vege', 'reconfort', 'france'] },
  { emoji: '🍋', nom: 'Cake au citron', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🍎', nom: 'Pommes au four', type: 'dessert', tags: ['vege', 'leger', 'reconfort', 'france'] },
  { emoji: '🍏', nom: 'Compote maison', type: 'dessert', tags: ['vege', 'leger', 'france'] },
  { emoji: '🍯', nom: 'Fromage blanc au miel', type: 'dessert', tags: ['rapide', 'vege', 'leger', 'france'] },
  { emoji: '🍓', nom: 'Fraises chantilly', type: 'dessert', tags: ['rapide', 'vege', 'leger', 'france'] },
  { emoji: '🍑', nom: 'Pêches rôties au miel', type: 'dessert', tags: ['rapide', 'vege', 'leger', 'france'] },
  { emoji: '🍊', nom: 'Salade d\'agrumes', type: 'dessert', tags: ['rapide', 'vege', 'leger', 'france'] },
  { emoji: '🍨', nom: 'Dame blanche', type: 'dessert', tags: ['rapide', 'vege', 'france'] },
  { emoji: '☕', nom: 'Café gourmand', type: 'dessert', tags: ['rapide', 'vege', 'france'] },
  { emoji: '🍋', nom: 'Sorbet citron', type: 'dessert', tags: ['rapide', 'vege', 'leger', 'france'] },
  { emoji: '🍨', nom: 'Nougat glacé', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🍦', nom: 'Omelette norvégienne', type: 'dessert', tags: ['vege', 'france'] },
  { emoji: '🍫', nom: 'Fondue au chocolat', type: 'dessert', tags: ['vege', 'reconfort', 'france'] },

  // ---------- Desserts du monde ----------
  { emoji: '☕', nom: 'Tiramisu', type: 'dessert', tags: ['vege', 'commande', 'monde'] },
  { emoji: '🍮', nom: 'Panna cotta aux fruits rouges', type: 'dessert', tags: ['monde'] },
  { emoji: '🍨', nom: 'Affogato', type: 'dessert', tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🥐', nom: 'Cannoli siciliens', type: 'dessert', tags: ['vege', 'commande', 'monde'] },
  { emoji: '🍰', nom: 'Cheesecake new-yorkais', type: 'dessert', tags: ['vege', 'monde'] },
  { emoji: '🍰', nom: 'Cheesecake japonais soufflé', type: 'dessert', tags: ['vege', 'monde'] },
  { emoji: '🍫', nom: 'Brownies', type: 'dessert', tags: ['vege', 'reconfort', 'monde'] },
  { emoji: '🍪', nom: 'Cookies tout chauds', type: 'dessert', tags: ['rapide', 'vege', 'reconfort', 'monde'] },
  { emoji: '🥕', nom: 'Carrot cake', type: 'dessert', tags: ['vege', 'monde'] },
  { emoji: '🍌', nom: 'Banana bread', type: 'dessert', tags: ['vege', 'reconfort', 'monde'] },
  { emoji: '🥞', nom: 'Pancakes au sirop d\'érable', type: 'dessert', tags: ['rapide', 'vege', 'reconfort', 'monde'] },
  { emoji: '🥧', nom: 'Apple pie', type: 'dessert', tags: ['vege', 'reconfort', 'monde'] },
  { emoji: '🍎', nom: 'Crumble pommes-fruits rouges', type: 'dessert', tags: ['vege', 'reconfort', 'monde'] },
  { emoji: '🍮', nom: 'Sticky toffee pudding', type: 'dessert', tags: ['vege', 'reconfort', 'monde'] },
  { emoji: '🍌', nom: 'Banoffee pie', type: 'dessert', tags: ['vege', 'monde'] },
  { emoji: '🍋', nom: 'Key lime pie', type: 'dessert', tags: ['vege', 'monde'] },
  { emoji: '🍓', nom: 'Pavlova aux fruits rouges', type: 'dessert', tags: ['vege', 'leger', 'monde'] },
  { emoji: '🍎', nom: 'Strudel aux pommes', type: 'dessert', tags: ['vege', 'monde'] },
  { emoji: '🍒', nom: 'Forêt-noire', type: 'dessert', tags: ['vege', 'monde'] },
  { emoji: '🥞', nom: 'Kaiserschmarrn', type: 'dessert', tags: ['vege', 'reconfort', 'monde'] },
  { emoji: '🍩', nom: 'Donuts', type: 'dessert', tags: ['vege', 'commande', 'monde'] },
  { emoji: '🧁', nom: 'Muffins aux myrtilles', type: 'dessert', tags: ['vege', 'monde'] },
  { emoji: '🥖', nom: 'Churros & chocolat chaud', type: 'dessert', tags: ['vege', 'reconfort', 'commande', 'monde'] },
  { emoji: '🍮', nom: 'Crème catalane', type: 'dessert', tags: ['vege', 'monde'] },
  { emoji: '🥧', nom: 'Pastéis de nata', type: 'dessert', tags: ['vege', 'commande', 'monde'] },
  { emoji: '🥛', nom: 'Tres leches', type: 'dessert', tags: ['vege', 'monde'] },
  { emoji: '🍫', nom: 'Brigadeiros', type: 'dessert', tags: ['rapide', 'vege', 'monde'] },
  { emoji: '🍯', nom: 'Baklava', type: 'dessert', tags: ['vege', 'commande', 'monde'] },
  { emoji: '🌙', nom: 'Cornes de gazelle', type: 'dessert', tags: ['vege', 'commande', 'monde'] },
  { emoji: '🍊', nom: 'Oranges à la cannelle', type: 'dessert', tags: ['rapide', 'vege', 'leger', 'monde'] },
  { emoji: '🌸', nom: 'Mhalabiya à la fleur d\'oranger', type: 'dessert', tags: ['vege', 'leger', 'monde'] },
  { emoji: '🍡', nom: 'Mochis glacés', type: 'dessert', tags: ['vege', 'commande', 'monde'] },
  { emoji: '🥞', nom: 'Dorayaki', type: 'dessert', tags: ['vege', 'monde'] },
  { emoji: '🍵', nom: 'Glace au thé matcha', type: 'dessert', tags: ['vege', 'monde'] },
  { emoji: '🍧', nom: 'Bingsu', type: 'dessert', tags: ['vege', 'monde'] },
  { emoji: '🥥', nom: 'Perles de coco', type: 'dessert', tags: ['vege', 'commande', 'monde'] },
  { emoji: '🥭', nom: 'Mango sticky rice', type: 'dessert', tags: ['vege', 'commande', 'monde'] },
  { emoji: '🍩', nom: 'Gulab jamun', type: 'dessert', tags: ['vege', 'commande', 'monde'] },
  { emoji: '🥭', nom: 'Lassi à la mangue', type: 'dessert', tags: ['rapide', 'vege', 'leger', 'monde'] },
  { emoji: '🧀', nom: 'Knafeh', type: 'dessert', tags: ['vege', 'commande', 'monde'] },
  { emoji: '🍫', nom: 'Mug cake au chocolat', type: 'dessert', tags: ['rapide', 'vege', 'reconfort', 'monde'] },
  { emoji: '🥣', nom: 'Yaourt grec, granola & fruits', type: 'dessert', tags: ['rapide', 'vege', 'leger', 'monde'] },
  { emoji: '🫐', nom: 'Smoothie bowl', type: 'dessert', tags: ['rapide', 'vege', 'leger', 'monde'] },

  // ---------- Pour les flemmards ----------
  { emoji: '🍫', nom: 'Juste un carré de chocolat', type: 'dessert', tags: ['rapide', 'vege', 'leger'] },
  { emoji: '🍨', nom: 'Pot de glace devant un film', type: 'dessert', tags: ['rapide', 'vege', 'reconfort'] },
];
